### ISSUE TITLE
Cannot build mixed-java-kotlin-hello-world

### ISSUE THREAD

**Issue by jmfayard** [JetBrains/kotlin-examples#7]
Ok, next step, getting mixed-java-kotlin-hello-world to work in IntelliJ 14

I have a branch https://github.com/jmfayard/kotlin-examples/tree/issue7 that
- add missing documentation
- fix apply plugin: 'android' 
- fix gradle build tools 0.8 (unsupported)
- still is not enough, gradle failing with this error

````
$ ./gradlew tasks --stacktrace

org.gradle.api.GradleScriptException: A problem occurred evaluating project ':AndroidSample'.
....
Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
at com.android.build.gradle.BasePlugin.getLocalVersion(BasePlugin.groovy:491)
at com.android.build.gradle.BasePlugin.<init>(BasePlugin.groovy:129)
at com.android.build.gradle.AppPlugin.<init>(AppPlugin.groovy:40)
at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:62)
at org.gradle.api.internal.plugins.DefaultPluginRegistry.loadPlugin(DefaultPluginRegistry.java:67)
```

**Comment by jmfayard** [comment]
I wonder if this is correct
`maven {      url 'http://oss.sonatype.org/content/repositories/snapshots'    } `

the event log shows me
```
13:01:10 Unindexed remote maven repositories found. Disable...
         The following repositories used in your gradle projects were not indexed yet: 
         http://oss.sonatype.org/content/repositories/snapshots
         If you want to use dependency completion for these repositories artifacts,
         Open Repositories List, select required repositories and press "Update" button
```

but when I do press "Update", I get this

![screen shot 2015-05-03 at 13 02 21](https://cloud.githubusercontent.com/assets/459464/7444788/b4b509ac-f194-11e4-912d-ca81676a96b1.png)

**Comment by NataliaUkhorskaya** [comment]
@jmfayard The problem is that com.android.application plugin 1.1.0 requires gradle 2.1, so you should also update gradle-wrapper.jar
